name: TagToRelease
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Process
    runs-on: ubuntu-latest
    steps:
      # setup PHP action
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.36.0
        with:
          php-version: '8.1'
          tools: composer

      # parse vx.x.x from the tag ref to be used later
      # https://github.community/t/how-to-get-just-the-tag-name/16241/5
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      # checkout the code, defaults to correct tags etc. automatically
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v6

      # install dependencies with composer and dump autoload
      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      # create zip package
      - name: Create zip package
        run: |
          mkdir -p release/maksuturva
          rsync -arv --exclude='release' --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release/maksuturva/
          cd release
          zip -r ${{ steps.get_version.outputs.VERSION }}-maksuturva.zip maksuturva/

      # create release and upload assets
      # https://github.com/softprops/action-gh-release
      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: ./release/${{ steps.get_version.outputs.VERSION }}-maksuturva.zip
